### ISSUE TITLE
not an issue but is it possible on rog ally to use wmi to adjust wattage rather than ryzenadj?

### ISSUE THREAD

**Issue by ripplingsnake** [aarron-lee/SimpleDeckyTDP#16] opened 2024-01-02 15:27 UTC
as tilt , ryzenadj interfers with alot can you make a version with direct control over mwi?

**Comment by aarron-lee** [comment] 2024-01-02 21:03
> as tilt , ryzenadj interfers with alot can you make a version with direct control over mwi?

Hrm, so there's 2 options that could be done here:

1. Override ryzenadj and use your own script for to set TDP. There's an option to do so, documented [here](https://github.com/aarron-lee/SimpleDeckyTDP#custom-tdp-method)
2. I could try to add a device-specific implementation, such as the one for the legion_go documented [here](https://github.com/aarron-lee/SimpleDeckyTDP/tree/main/py_modules/devices). However, I don't have a ROG Ally, so I'd need someone who is willing to help develop + test it.

**Comment by aarron-lee** [comment] 2024-02-28 21:24
a user is testing the feature now, it should be released in the next day or so

**Comment by aarron-lee** [comment] 2024-03-05 18:06
as a followup, currently can't roll out this feature due to it causing some suspend issues on the ROG Ally. I'll enable the feature if I figure out what the issue is.

**Comment by aarron-lee** [comment] 2024-03-13 03:19
asus wmi has been added in 0.2.4

**Closed by aarron-lee** 2024-03-13 03:19 UTC
